/* ============================================================================
 * NUMBER LOGIC — CLASSIFICATIONS
 * ============================================================================
 *
 * Maps each question id to its pattern category, technique, and formula.
 */

var PATTERN_INFO = {
  "alternating-ops":    { full: "Alternating Operations",  weapon: "identify the two operations and their cycle" },
  "interleaved":        { full: "Interleaved Sequences",   weapon: "split odd/even positions into separate sequences" },
  "cyclic-ops":         { full: "Cyclic Operations",       weapon: "identify the repeating cycle of operations" },
  "arithmetic-2nd-diff":{ full: "Quadratic / 2nd Differences", weapon: "take second differences — they should be constant" },
  "famous-diff":        { full: "Famous Difference Pattern", weapon: "recognise the difference sequence (primes, Fibonacci, etc.)" },
  "geometric-diff":     { full: "Geometric Differences",   weapon: "differences multiply by a constant ratio" },
  "pair-subtract":      { full: "Pair Subtraction",        weapon: "group into pairs, subtract to get next" },
  "linear-recurrence":  { full: "Linear Recurrence",       weapon: "each term is a fixed combination of previous terms" },
  "recursive-product":  { full: "Recursive Product",       weapon: "each term involves multiplying previous terms" },
  "fraction-chain":     { full: "Fraction Chain",          weapon: "track numerator and denominator patterns separately" },
  "prime-selection":    { full: "Prime Number Pattern",    weapon: "terms are primes or derived from primes" },
  "representation-count":{ full: "Representation Count",   weapon: "each value appears a specific number of times in different forms" },
  "complex-ratio":      { full: "Complex Ratio",           weapon: "consecutive ratios follow a convergent pattern" },
  "factorial":          { full: "Factorial",               weapon: "terms are n! — multiply by increasing integers" },
  "power-pattern":      { full: "Power Pattern",           weapon: "terms are powers like nⁿ, n², n³" }
};

var CLASSIFY = {
  "seq-p01": { p: "alternating-ops",     t: "Alternating ÷3 and ×2",             f: "a(2k+1) = a(2k) ÷ 3, a(2k+2) = a(2k+1) × 2" },
  "seq-p02": { p: "interleaved",         t: "Two interleaved arithmetic sequences", f: "Odd: +20. Even: num +16, den +4" },
  "seq-p03": { p: "cyclic-ops",          t: "3-cycle: ×2, +10, ÷4",             f: "Operations repeat every 3 terms" },
  "seq-p04": { p: "representation-count",t: "Value n appears (n−3) times",       f: "4×1, 5×2, 6×3, 7×4 representations" },
  "seq-p05": { p: "cyclic-ops",          t: "4-cycle: −1, +2, ×3, ÷4",          f: "Operations repeat every 4 terms" },
  "seq-p06": { p: "arithmetic-2nd-diff", t: "Constant 2nd difference of 4",      f: "Δ² = 4, diffs: 20, 24, 28, 32, 36" },
  "seq-p07": { p: "pair-subtract",       t: "Subtract pairs",                    f: "a(2k+1) − a(2k+2) = a(2k+3)" },
  "seq-p08": { p: "famous-diff",         t: "Fibonacci differences",             f: "Δ = 1, 1, 2, 3, 5, 8 (Fibonacci)" },
  "seq-p09": { p: "geometric-diff",      t: "Differences ×(−2)",                 f: "Δ = −1, 2, −4, 8, −16, −32" },
  "seq-p10": { p: "alternating-ops",     t: "Alternating +2 and ×2",             f: "a(2k+1) = a(2k) + 2, a(2k+2) = a(2k+1) × 2" },
  "seq-p11": { p: "alternating-ops",     t: "Decreasing ÷/× factors",           f: "÷6, ×5, ÷4, ×3, ÷2, ×1" },
  "seq-p12": { p: "famous-diff",         t: "Prime differences",                 f: "Δ = 2, 3, 5, 7, 11, 13 (primes)" },
  "seq-p13": { p: "cyclic-ops",          t: "3-cycle: ÷3, ÷2, +1",              f: "Operations repeat every 3 terms" },
  "seq-p14": { p: "alternating-ops",     t: "Alternating multiply/add",          f: "×2 and +small, with halving adds" },
  "seq-p15": { p: "complex-ratio",       t: "Convergent ratio sequence",         f: "Ratios approach 3; differences accelerate" },
  "seq-p16": { p: "interleaved",         t: "Odd ×⅔, Even ×3/2",               f: "Split positions, each is geometric" },
  "seq-p17": { p: "recursive-product",   t: "Each = product of two before",      f: "a(n) = a(n−1) × a(n−2)" },
  "seq-p18": { p: "interleaved",         t: "Interleaved fraction sequences",    f: "Odd: num+2/den+6. Even: num+1/den+3" },
  "seq-p19": { p: "prime-selection",     t: "Every other prime",                 f: "1st, 3rd, 5th, … prime" },
  "seq-p20": { p: "cyclic-ops",          t: "3-cycle: ÷3, ×6, ×⅔",             f: "Operations repeat every 3 terms" },
  "seq-p21": { p: "recursive-product",   t: "Multiply by (previous − 1)",       f: "a(n) = a(n−1) × (a(n−2) − 1)" },
  "seq-p22": { p: "linear-recurrence",   t: "a(n) = a(n−1) + 3·a(n−2)",         f: "Linear recurrence with multiplier 3" },
  "seq-p23": { p: "fraction-chain",      t: "Numerator = prev denominator",      f: "Gap doubles in pairs: 1,1,2,2,4,4,8" },
  "seq-p24": { p: "interleaved",         t: "Odd +3, Even ×3",                  f: "Two independent sequences at alternating positions" },

  "seq-g01": { p: "alternating-ops",     t: "Alternating ×3 and −5",             f: "a(2k+1) = a(2k) × 3, a(2k+2) = a(2k+1) − 5" },
  "seq-g02": { p: "alternating-ops",     t: "Alternating ×3 and −3",             f: "a(2k+1) = a(2k) × 3, a(2k+2) = a(2k+1) − 3" },
  "seq-g03": { p: "alternating-ops",     t: "Alternating ×4 and ×2",             f: "a(2k+1) = a(2k) × 4, a(2k+2) = a(2k+1) × 2" },
  "seq-g04": { p: "alternating-ops",     t: "Alternating ÷2 and +5",             f: "a(2k+1) = a(2k) ÷ 2, a(2k+2) = a(2k+1) + 5" },
  "seq-g05": { p: "alternating-ops",     t: "Alternating ×4 and −4",             f: "a(2k+1) = a(2k) × 4, a(2k+2) = a(2k+1) − 4" },
  "seq-g06": { p: "interleaved",         t: "Perfect squares / arithmetic",      f: "Odd: n². Even: −5 each" },
  "seq-g07": { p: "interleaved",         t: "Powers of 2 / powers of 3",         f: "Odd: ×2. Even: ×3" },
  "seq-g08": { p: "interleaved",         t: "Odd +5, Even +2",                  f: "Two arithmetic sequences" },
  "seq-g09": { p: "interleaved",         t: "Constant 1 / doubling",            f: "Odd: always 1. Even: ×2" },
  "seq-g10": { p: "geometric-diff",      t: "Differences = 2ⁿ − 1",             f: "Δ doubles+1: 1, 3, 7, 15, 31, 63" },
  "seq-g11": { p: "geometric-diff",      t: "Differences double",               f: "Δ = 1, 2, 4, 8, 16, 32" },
  "seq-g12": { p: "geometric-diff",      t: "2ⁿ − 1",                           f: "Δ doubles: 2, 4, 8, 16, 32, 64" },
  "seq-g13": { p: "geometric-diff",      t: "Differences double",               f: "Δ = 1, 2, 4, 8, 16, 32" },
  "seq-g14": { p: "geometric-diff",      t: "Differences double",               f: "Δ = 3, 6, 12, 24, 48, 96" },
  "seq-g15": { p: "cyclic-ops",          t: "3-cycle operations",               f: "×3, ÷2, ÷3 or similar cycle" },
  "seq-g16": { p: "cyclic-ops",          t: "3-cycle: +1, ×3, ÷2",              f: "Operations repeat every 3 terms" },
  "seq-g17": { p: "cyclic-ops",          t: "2-cycle: ×2, −3",                  f: "Operations repeat every 2 terms" },
  "seq-g18": { p: "cyclic-ops",          t: "3-cycle: ×3, ×3, −2",              f: "Operations repeat every 3 terms" },
  "seq-g19": { p: "pair-subtract",       t: "Subtract pairs",                    f: "a(2k+1) − a(2k+2) = a(2k+3)" },
  "seq-g20": { p: "pair-subtract",       t: "Subtract pairs",                    f: "a(2k+1) − a(2k+2) = a(2k+3)" },
  "seq-g21": { p: "linear-recurrence",   t: "Fibonacci",                        f: "a(n) = a(n−1) + a(n−2)" },
  "seq-g22": { p: "linear-recurrence",   t: "Fibonacci-like from 2,1",          f: "a(n) = a(n−1) + a(n−2)" },
  "seq-g23": { p: "linear-recurrence",   t: "Every other Fibonacci",            f: "a(n) = 3a(n−1) − a(n−2)" },
  "seq-g24": { p: "recursive-product",   t: "Mixed multiplicative",             f: "Multiplicative recurrence" },
  "seq-g25": { p: "famous-diff",         t: "Perfect squares",                  f: "a(n) = n², Δ = 3, 5, 7, 9, 11, 13" },
  "seq-g26": { p: "famous-diff",         t: "Perfect cubes",                    f: "a(n) = n³" },
  "seq-g27": { p: "famous-diff",         t: "Oblong numbers n(n+1)",            f: "Δ = 4, 6, 8, 10, 12, 14" },
  "seq-g28": { p: "famous-diff",         t: "Triangular numbers",               f: "a(n) = n(n+1)/2, Δ = 2,3,4,5,6,7" },
  "seq-g29": { p: "linear-recurrence",   t: "Fibonacci from 0",                f: "a(n) = a(n−1) + a(n−2)" },
  "seq-g30": { p: "arithmetic-2nd-diff", t: "n² − 1",                           f: "Δ² = 2, diffs: 5, 7, 9, 11, 13, 15" },
  "seq-g31": { p: "arithmetic-2nd-diff", t: "Squares from 2²",                  f: "Δ = 5, 7, 9, 11, 13" },
  "seq-g32": { p: "arithmetic-2nd-diff", t: "n² + 1",                           f: "Δ = 3, 5, 7, 9, 11, 13" },
  "seq-g33": { p: "fraction-chain",      t: "Fibonacci fractions",              f: "num=prev den, den=num+den" },
  "seq-g34": { p: "fraction-chain",      t: "n / n(n+1)",                       f: "Numerator +1, denominator = n(n+1)" },
  "seq-g35": { p: "prime-selection",     t: "Twice the primes",                 f: "a(n) = 2 × p(n)" },
  "seq-g36": { p: "prime-selection",     t: "Every other prime from 2nd",       f: "p(2), p(4), p(6), p(8), …" },
  "seq-g37": { p: "factorial",           t: "Factorials",                       f: "a(n) = n!" },
  "seq-g38": { p: "arithmetic-2nd-diff", t: "Centered hexagonal numbers",       f: "Δ = 2, 4, 6, 8, 10, 12" },
  "seq-g39": { p: "prime-selection",     t: "Consecutive primes",               f: "p(1), p(2), p(3), …" },
  "seq-g40": { p: "power-pattern",       t: "n to the n",                       f: "a(n) = nⁿ" },
  "seq-g41": { p: "alternating-ops",     t: "Alternating +1 and ×3",             f: "a(2k+1) = a(2k) + 1, a(2k+2) = a(2k+1) × 3" },
  "seq-g42": { p: "alternating-ops",     t: "Alternating +2 and ×3",             f: "a(2k+1) = a(2k) + 2, a(2k+2) = a(2k+1) × 3" },
  "seq-g43": { p: "alternating-ops",     t: "Alternating ÷2 and +5",             f: "a(2k+1) = a(2k) ÷ 2, a(2k+2) = a(2k+1) + 5" },
  "seq-g44": { p: "interleaved",         t: "Cubes / halving powers of 2",      f: "Odd: n³. Even: ÷2 from 64" },
  "seq-g45": { p: "interleaved",         t: "Two square sequences",             f: "Odd: (n−1)². Even: n²" },
  "seq-g46": { p: "cyclic-ops",          t: "3-cycle: +2, ×3, ÷2",              f: "Operations repeat every 3 terms" },
  "seq-g47": { p: "cyclic-ops",          t: "3-cycle: ×3, −3, ÷3",              f: "Operations repeat every 3 terms" },
  "seq-g48": { p: "linear-recurrence",   t: "Fibonacci-like from 1,3",          f: "a(n) = a(n−1) + a(n−2)" },
  "seq-g49": { p: "linear-recurrence",   t: "Tribonacci",                       f: "a(n) = a(n−1) + a(n−2) + a(n−3)" },
  "seq-g50": { p: "linear-recurrence",   t: "Double plus one",                  f: "a(n) = 2·a(n−1) + 1" }
};
