/* ============================================================================
 * NUMBER LOGIC — CLASSIFICATIONS
 * ============================================================================
 *
 * Maps each question id to its pattern category, technique, and formula.
 */

var PATTERN_INFO = {
  "alternating-ops":    { full: "Alternating Operations",  weapon: "identify the two operations and their cycle" },
  "interleaved":        { full: "Interleaved Sequences",   weapon: "split odd/even positions into separate sequences" },
  "cyclic-ops":         { full: "Cyclic Operations",       weapon: "identify the repeating cycle of operations" },
  "arithmetic-2nd-diff":{ full: "Quadratic / 2nd Differences", weapon: "take second differences — they should be constant" },
  "famous-diff":        { full: "Famous Difference Pattern", weapon: "recognise the difference sequence (primes, Fibonacci, etc.)" },
  "geometric-diff":     { full: "Geometric Differences",   weapon: "differences multiply by a constant ratio" },
  "pair-subtract":      { full: "Pair Subtraction",        weapon: "group into pairs, subtract to get next" },
  "linear-recurrence":  { full: "Linear Recurrence",       weapon: "each term is a fixed combination of previous terms" },
  "recursive-product":  { full: "Recursive Product",       weapon: "each term involves multiplying previous terms" },
  "fraction-chain":     { full: "Fraction Chain",          weapon: "track numerator and denominator patterns separately" },
  "prime-selection":    { full: "Prime Number Pattern",    weapon: "terms are primes or derived from primes" },
  "representation-count":{ full: "Representation Count",   weapon: "each value appears a specific number of times in different forms" },
  "complex-ratio":      { full: "Complex Ratio",           weapon: "consecutive ratios follow a convergent pattern" },
  "factorial":          { full: "Factorial",               weapon: "terms are n! — multiply by increasing integers" },
  "power-pattern":      { full: "Power Pattern",           weapon: "terms are powers like nⁿ, n², n³" },
  "progressive-ops":    { full: "Progressive Operations",  weapon: "operations change or grow each step — not a fixed cycle" },
  "combinatorial":      { full: "Combinatorial Sequence",  weapon: "recognise a named counting sequence (Catalan, Bell, Motzkin, partitions, derangements)" },
  "number-theoretic":   { full: "Number-Theoretic",        weapon: "terms depend on divisors, totients, or other number-theoretic functions" },
  "digit-pattern":      { full: "Digit Pattern",           weapon: "rule involves digit sums, digit products, or binary representation" },
  "compound":           { full: "Compound Pattern",        weapon: "combines two or more pattern families — decompose to identify each" }
};

var CLASSIFY = {
  "seq-p01": { p: "alternating-ops",     t: "Alternating ÷3 and ×2",             f: "a(2k+1) = a(2k) ÷ 3, a(2k+2) = a(2k+1) × 2" },
  "seq-p02": { p: "interleaved",         t: "Two interleaved arithmetic sequences", f: "Odd: +20. Even: num +16, den +4" },
  "seq-p03": { p: "cyclic-ops",          t: "3-cycle: ×2, +10, ÷4",             f: "Operations repeat every 3 terms" },
  "seq-p04": { p: "representation-count",t: "Value n appears (n−3) times",       f: "4×1, 5×2, 6×3, 7×4 representations" },
  "seq-p05": { p: "cyclic-ops",          t: "4-cycle: −1, +2, ×3, ÷4",          f: "Operations repeat every 4 terms" },
  "seq-p06": { p: "arithmetic-2nd-diff", t: "Constant 2nd difference of 4",      f: "Δ² = 4, diffs: 20, 24, 28, 32, 36" },
  "seq-p07": { p: "pair-subtract",       t: "Subtract pairs",                    f: "a(2k+1) − a(2k+2) = a(2k+3)" },
  "seq-p08": { p: "famous-diff",         t: "Fibonacci differences",             f: "Δ = 1, 1, 2, 3, 5, 8 (Fibonacci)" },
  "seq-p09": { p: "geometric-diff",      t: "Differences ×(−2)",                 f: "Δ = −1, +2, −4, +8, −16 (absolute values double, signs alternate)" },
  "seq-p10": { p: "alternating-ops",     t: "Alternating +2 and ×2",             f: "a(2k+1) = a(2k) + 2, a(2k+2) = a(2k+1) × 2" },
  "seq-p11": { p: "alternating-ops",     t: "Decreasing ÷/× factors",           f: "÷6, ×5, ÷4, ×3, ÷2, ×1" },
  "seq-p12": { p: "famous-diff",         t: "Prime differences",                 f: "Δ = 2, 3, 5, 7, 11, 13 (primes)" },
  "seq-p13": { p: "cyclic-ops",          t: "3-cycle: ÷3, ÷2, +1",              f: "Operations repeat every 3 terms" },
  "seq-p14": { p: "alternating-ops",     t: "Paired large/small jumps",          f: "Large diffs +32 each; small diffs halve (8, 4, 8)" },
  "seq-p15": { p: "complex-ratio",       t: "Convergent ratio sequence",         f: "Ratios approach 3; differences accelerate" },
  "seq-p16": { p: "interleaved",         t: "Odd ×⅔, Even ×3/2",               f: "Split positions, each is geometric" },
  "seq-p17": { p: "recursive-product",   t: "Each = product of two before",      f: "a(n) = a(n−1) × a(n−2)" },
  "seq-p18": { p: "interleaved",         t: "Interleaved fraction sequences",    f: "Odd: num+2/den+6. Even: num+1/den+3" },
  "seq-p19": { p: "prime-selection",     t: "Every other prime",                 f: "1st, 3rd, 5th, … prime" },
  "seq-p20": { p: "cyclic-ops",          t: "3-cycle: ÷3, ×6, ×⅔",             f: "Operations repeat every 3 terms" },
  "seq-p21": { p: "recursive-product",   t: "Multiply by (previous − 1)",       f: "a(n) = a(n−1) × (a(n−2) − 1)" },
  "seq-p22": { p: "linear-recurrence",   t: "a(n) = a(n−1) + 3·a(n−2)",         f: "Linear recurrence with multiplier 3" },
  "seq-p23": { p: "fraction-chain",      t: "Numerator = prev denominator",      f: "Gap doubles in pairs: 1,1,2,2,4,4,8" },
  "seq-p24": { p: "interleaved",         t: "Odd +3, Even ×3",                  f: "Two independent sequences at alternating positions" },

  "seq-g01": { p: "alternating-ops",     t: "Alternating ×3 and −5",             f: "a(2k+1) = a(2k) × 3, a(2k+2) = a(2k+1) − 5" },
  "seq-g02": { p: "alternating-ops",     t: "Alternating ×3 and −3",             f: "a(2k+1) = a(2k) × 3, a(2k+2) = a(2k+1) − 3" },
  "seq-g03": { p: "alternating-ops",     t: "Alternating ×4 and ×2",             f: "a(2k+1) = a(2k) × 4, a(2k+2) = a(2k+1) × 2" },
  "seq-g04": { p: "alternating-ops",     t: "Alternating ÷2 and +5",             f: "a(2k+1) = a(2k) ÷ 2, a(2k+2) = a(2k+1) + 5" },
  "seq-g05": { p: "alternating-ops",     t: "Alternating ×4 and −4",             f: "a(2k+1) = a(2k) × 4, a(2k+2) = a(2k+1) − 4" },
  "seq-g06": { p: "interleaved",         t: "Perfect squares / arithmetic",      f: "Odd: n². Even: −5 each" },
  "seq-g07": { p: "interleaved",         t: "Powers of 2 / powers of 3",         f: "Odd: ×2. Even: ×3" },
  "seq-g08": { p: "interleaved",         t: "Odd +5, Even +2",                  f: "Two arithmetic sequences" },
  "seq-g09": { p: "interleaved",         t: "Constant 1 / doubling",            f: "Odd: always 1. Even: ×2" },
  "seq-g10": { p: "geometric-diff",      t: "Differences = 2ⁿ − 1",             f: "Δ doubles+1: 1, 3, 7, 15, 31, 63" },
  "seq-g11": { p: "geometric-diff",      t: "Differences double",               f: "Δ = 1, 2, 4, 8, 16, 32" },
  "seq-g12": { p: "geometric-diff",      t: "2ⁿ − 1",                           f: "Δ doubles: 2, 4, 8, 16, 32, 64" },
  "seq-g13": { p: "geometric-diff",      t: "Differences double",               f: "Δ = 1, 2, 4, 8, 16, 32" },
  "seq-g14": { p: "geometric-diff",      t: "Differences double",               f: "Δ = 3, 6, 12, 24, 48, 96" },
  "seq-g15": { p: "cyclic-ops",          t: "3-cycle: ×2, −5, +3",              f: "Operations repeat every 3 terms" },
  "seq-g16": { p: "cyclic-ops",          t: "3-cycle: +1, ×3, ÷2",              f: "Operations repeat every 3 terms" },
  "seq-g17": { p: "cyclic-ops",          t: "2-cycle: ×2, −3",                  f: "Operations repeat every 2 terms" },
  "seq-g18": { p: "cyclic-ops",          t: "3-cycle: ×3, ×3, −2",              f: "Operations repeat every 3 terms" },
  "seq-g19": { p: "pair-subtract",       t: "Subtract pairs",                    f: "a(2k+1) − a(2k+2) = a(2k+3)" },
  "seq-g20": { p: "pair-subtract",       t: "Subtract pairs",                    f: "a(2k+1) − a(2k+2) = a(2k+3)" },
  "seq-g21": { p: "linear-recurrence",   t: "Fibonacci",                        f: "a(n) = a(n−1) + a(n−2)" },
  "seq-g22": { p: "linear-recurrence",   t: "Fibonacci-like from 2,1",          f: "a(n) = a(n−1) + a(n−2)" },
  "seq-g23": { p: "linear-recurrence",   t: "Every other Fibonacci",            f: "a(n) = 3a(n−1) − a(n−2)" },
  "seq-g24": { p: "recursive-product",   t: "Product of previous two",          f: "a(n) = a(n−1) × a(n−2)" },
  "seq-g25": { p: "famous-diff",         t: "Perfect squares",                  f: "a(n) = n², Δ = 3, 5, 7, 9, 11, 13" },
  "seq-g26": { p: "famous-diff",         t: "Perfect cubes",                    f: "a(n) = n³" },
  "seq-g27": { p: "famous-diff",         t: "Oblong numbers n(n+1)",            f: "Δ = 4, 6, 8, 10, 12, 14" },
  "seq-g28": { p: "famous-diff",         t: "Triangular numbers",               f: "a(n) = n(n+1)/2, Δ = 2,3,4,5,6,7" },
  "seq-g29": { p: "linear-recurrence",   t: "Fibonacci from 0",                f: "a(n) = a(n−1) + a(n−2)" },
  "seq-g30": { p: "arithmetic-2nd-diff", t: "n² − 1",                           f: "Δ² = 2, diffs: 5, 7, 9, 11, 13, 15" },
  "seq-g31": { p: "arithmetic-2nd-diff", t: "Squares from 2²",                  f: "Δ = 5, 7, 9, 11, 13" },
  "seq-g32": { p: "arithmetic-2nd-diff", t: "n² + 1",                           f: "Δ = 3, 5, 7, 9, 11, 13" },
  "seq-g33": { p: "fraction-chain",      t: "Fibonacci fractions",              f: "num=prev den, den=num+den" },
  "seq-g34": { p: "fraction-chain",      t: "n / n(n+1)",                       f: "Numerator +1, denominator = n(n+1)" },
  "seq-g35": { p: "prime-selection",     t: "Twice the primes",                 f: "a(n) = 2 × p(n)" },
  "seq-g36": { p: "prime-selection",     t: "Every other prime from 2nd",       f: "p(2), p(4), p(6), p(8), …" },
  "seq-g37": { p: "factorial",           t: "Factorials",                       f: "a(n) = n!" },
  "seq-g38": { p: "arithmetic-2nd-diff", t: "Centered hexagonal numbers",       f: "Δ = 2, 4, 6, 8, 10, 12" },
  "seq-g39": { p: "prime-selection",     t: "Consecutive primes",               f: "p(1), p(2), p(3), …" },
  "seq-g40": { p: "power-pattern",       t: "n to the n",                       f: "a(n) = nⁿ" },
  "seq-g41": { p: "alternating-ops",     t: "Alternating +1 and ×3",             f: "a(2k+1) = a(2k) + 1, a(2k+2) = a(2k+1) × 3" },
  "seq-g42": { p: "alternating-ops",     t: "Alternating +2 and ×3",             f: "a(2k+1) = a(2k) + 2, a(2k+2) = a(2k+1) × 3" },
  "seq-g43": { p: "alternating-ops",     t: "Alternating ÷2 and +5",             f: "a(2k+1) = a(2k) ÷ 2, a(2k+2) = a(2k+1) + 5" },
  "seq-g44": { p: "interleaved",         t: "Cubes / halving powers of 2",      f: "Odd: n³. Even: ÷2 from 64" },
  "seq-g45": { p: "interleaved",         t: "Two square sequences",             f: "Odd: (n−1)². Even: n²" },
  "seq-g46": { p: "cyclic-ops",          t: "3-cycle: +2, ×3, ÷2",              f: "Operations repeat every 3 terms" },
  "seq-g47": { p: "cyclic-ops",          t: "3-cycle: ×2, +5, −3",              f: "Operations repeat every 3 terms" },
  "seq-g48": { p: "linear-recurrence",   t: "Fibonacci-like from 1,3",          f: "a(n) = a(n−1) + a(n−2)" },
  "seq-g49": { p: "linear-recurrence",   t: "Tribonacci",                       f: "a(n) = a(n−1) + a(n−2) + a(n−3)" },
  "seq-g50": { p: "linear-recurrence",   t: "Double plus one",                  f: "a(n) = 2·a(n−1) + 1" },

  "seq-m01": { p: "alternating-ops",     t: "Alternating ×2 and −1",             f: "a(2k+1) = a(2k) × 2, a(2k+2) = a(2k+1) − 1" },
  "seq-m02": { p: "alternating-ops",     t: "Alternating −2 and ×5",             f: "a(2k+1) = a(2k) − 2, a(2k+2) = a(2k+1) × 5" },
  "seq-m03": { p: "alternating-ops",     t: "Alternating ×3 and +1",             f: "a(2k+1) = a(2k) × 3, a(2k+2) = a(2k+1) + 1" },
  "seq-m04": { p: "alternating-ops",     t: "Alternating ÷2 and +10",            f: "a(2k+1) = a(2k) ÷ 2, a(2k+2) = a(2k+1) + 10" },
  "seq-m05": { p: "alternating-ops",     t: "Alternating +4 and ÷2",             f: "a(2k+1) = a(2k) + 4, a(2k+2) = a(2k+1) ÷ 2" },
  "seq-m06": { p: "alternating-ops",     t: "Alternating ×2 and −7",             f: "a(2k+1) = a(2k) × 2, a(2k+2) = a(2k+1) − 7" },
  "seq-m07": { p: "alternating-ops",     t: "Alternating +3 and ×2",             f: "a(2k+1) = a(2k) + 3, a(2k+2) = a(2k+1) × 2" },
  "seq-m08": { p: "cyclic-ops",          t: "3-cycle: ×2, +3, −1",              f: "Operations repeat every 3 terms" },
  "seq-m09": { p: "cyclic-ops",          t: "3-cycle: +1, ×2, −3",              f: "Operations repeat every 3 terms" },
  "seq-m10": { p: "cyclic-ops",          t: "4-cycle: +1, ×2, +3, ×2",          f: "Operations repeat every 4 terms" },
  "seq-m11": { p: "cyclic-ops",          t: "3-cycle: ×3, −5, +2",              f: "Operations repeat every 3 terms" },
  "seq-m12": { p: "cyclic-ops",          t: "3-cycle: +2, ×3, −5",              f: "Operations repeat every 3 terms" },
  "seq-m13": { p: "interleaved",         t: "Odd squares / even +4",            f: "Odd: (2k−1)². Even: +4 each" },
  "seq-m14": { p: "interleaved",         t: "Three sub-sequences ×2/×3/×5",     f: "Pos 1,4: ×2. Pos 2,5: ×3. Pos 3,6: ×5" },
  "seq-m15": { p: "interleaved",         t: "Primes / factorials",              f: "Odd: consecutive primes. Even: n!" },
  "seq-m16": { p: "interleaved",         t: "Accelerating decrease / triangular",f: "Odd: diffs −5,−10,−15. Even: triangular" },
  "seq-m17": { p: "interleaved",         t: "Powers of 2 / perfect squares",    f: "Odd: 2ⁿ. Even: n²" },
  "seq-m18": { p: "linear-recurrence",   t: "Triple minus one",                 f: "a(n) = 3·a(n−1) − 1" },
  "seq-m19": { p: "linear-recurrence",   t: "a + 2b recurrence",               f: "a(n) = a(n−1) + 2·a(n−2)" },
  "seq-m20": { p: "linear-recurrence",   t: "Skip-2 recurrence",               f: "a(n) = a(n−1) + a(n−3)" },
  "seq-m21": { p: "linear-recurrence",   t: "Sum of previous three",            f: "a(n) = a(n−1) + a(n−2) + a(n−3)" },
  "seq-m22": { p: "linear-recurrence",   t: "a + b − c recurrence",            f: "a(n) = a(n−1) + a(n−2) − a(n−3)" },
  "seq-m23": { p: "arithmetic-2nd-diff", t: "Constant 2nd difference of 3",     f: "Δ = 3, 6, 9, 12, 15, 18" },
  "seq-m24": { p: "famous-diff",         t: "Triangular number differences",    f: "Δ = 1, 3, 6, 10, 15, 21 (triangular)" },
  "seq-m25": { p: "famous-diff",         t: "Square differences",               f: "Δ = 4, 9, 16, 25, 36 (n² from n=2)" },
  "seq-m26": { p: "geometric-diff",      t: "Differences triple",               f: "Δ = 1, 3, 9, 27, 81 (×3)" },
  "seq-m27": { p: "arithmetic-2nd-diff", t: "2nd differences +3",              f: "Δ² = 5, 8, 11, 14 (+3 each)" },
  "seq-m28": { p: "famous-diff",         t: "Prime differences",                f: "Δ = 2, 3, 5, 7, 11, 13 (primes)" },
  "seq-m29": { p: "geometric-diff",      t: "Differences are powers of 3",      f: "Δ = 1, 3, 9, 27, 81 (3ⁿ)" },
  "seq-m30": { p: "famous-diff",         t: "Tetrahedral numbers",              f: "C(n+2,3), Δ = triangular numbers" },
  "seq-m31": { p: "power-pattern",       t: "2ⁿ minus n",                      f: "a(n) = 2ⁿ − n" },
  "seq-m32": { p: "famous-diff",         t: "Products of consecutive pairs",    f: "(2k−1)×(2k), Δ = 10, 18, 26, 34 (+8)" },
  "seq-m33": { p: "arithmetic-2nd-diff", t: "n(n+3)/2",                        f: "Δ = 3, 4, 5, 6, 7, 8 (+1)" },
  "seq-m34": { p: "arithmetic-2nd-diff", t: "Hexagonal numbers",               f: "n(2n−1), Δ = 5, 9, 13, 17, 21 (+4)" },
  "seq-m35": { p: "arithmetic-2nd-diff", t: "Pentagonal numbers",              f: "n(3n−1)/2, Δ = 4, 7, 10, 13, 16 (+3)" },
  "seq-m36": { p: "fraction-chain",      t: "Num ×2, denom 2d−1",             f: "Numerators double, denominators: d(n) = 2·d(n−1) − 1" },
  "seq-m37": { p: "fraction-chain",      t: "(2ⁿ−1)/2ⁿ",                      f: "Both num and denom double+1 / double" },
  "seq-m38": { p: "fraction-chain",      t: "Even/odd fractions",              f: "Num: +2 (evens), den: +2 (odds)" },
  "seq-m39": { p: "geometric-diff",      t: "Geometric ratio 3/2",             f: "Each term × 3/2" },
  "seq-m40": { p: "alternating-ops",     t: "Alternating ×2 and ×3",           f: "a(2k+1) = a(2k) × 2, a(2k+2) = a(2k+1) × 3" },
  "seq-m41": { p: "geometric-diff",      t: "Differences double",               f: "Δ = 1, 2, 4, 8, 16, 32" },
  "seq-m42": { p: "progressive-ops",     t: "+1, ×2, +3, ×4, +5, ×6",         f: "Odd ops add (1,3,5…), even ops multiply (2,4,6…)" },
  "seq-m43": { p: "alternating-ops",     t: "Alternating ×2 and +1",           f: "a(2k+1) = a(2k) × 2, a(2k+2) = a(2k+1) + 1" },
  "seq-m44": { p: "interleaved",         t: "Squares / cubes",                 f: "Odd: n². Even: n³" },
  "seq-m45": { p: "arithmetic-2nd-diff", t: "Constant 2nd difference of 5",    f: "Δ = 5, 10, 15, 20, 25, 30" },
  "seq-m46": { p: "linear-recurrence",   t: "Fibonacci minus one",             f: "a(n) = a(n−1) + a(n−2) − 1" },
  "seq-m47": { p: "interleaved",         t: "Mersenne / squares",              f: "Odd: 2ⁿ−1. Even: n²" },
  "seq-m48": { p: "linear-recurrence",   t: "Double plus position",            f: "a(n) = 2·a(n−1) + n" },
  "seq-m49": { p: "interleaved",         t: "Two arithmetic: +2 / +3",         f: "Odd: 1, 3, 5, 7 (+2). Even: 2, 5, 8, 11 (+3)" },
  "seq-m50": { p: "arithmetic-2nd-diff", t: "Constant 2nd difference of 6",    f: "Δ = 6, 12, 18, 24, 30, 36" },

  "seq-h01": { p: "linear-recurrence",   t: "Sum of previous four",            f: "a(n) = a(n−1) + a(n−2) + a(n−3) + a(n−4)" },
  "seq-h02": { p: "linear-recurrence",   t: "2a + b recurrence",              f: "a(n) = 2·a(n−1) + a(n−2)" },
  "seq-h03": { p: "progressive-ops",     t: "Multiply by position minus prev", f: "a(n) = a(n−1)·n − a(n−2)" },
  "seq-h04": { p: "recursive-product",   t: "Add prev + product of two before",f: "a(n) = a(n−1) + a(n−2)·a(n−3)" },
  "seq-h05": { p: "recursive-product",   t: "Add prev + square of two-back",   f: "a(n) = a(n−1) + a(n−2)²" },
  "seq-h06": { p: "recursive-product",   t: "Product minus three-back",        f: "a(n) = a(n−1)·a(n−2) − a(n−3)" },
  "seq-h07": { p: "recursive-product",   t: "Product plus one",                f: "a(n) = a(n−1)·a(n−2) + 1" },
  "seq-h08": { p: "recursive-product",   t: "Square minus previous",           f: "a(n) = a(n−1)² − a(n−2)" },
  "seq-h09": { p: "linear-recurrence",   t: "Absolute diff + three-back",      f: "a(n) = |a(n−1) − a(n−2)| + a(n−3)" },
  "seq-h10": { p: "combinatorial",       t: "Catalan numbers",                 f: "C(n) = C(2n,n)/(n+1)" },
  "seq-h11": { p: "combinatorial",       t: "Derangements",                    f: "D(n) = (n−1)·(D(n−1) + D(n−2))" },
  "seq-h12": { p: "combinatorial",       t: "Motzkin numbers",                 f: "M(n) = ((2n+1)·M(n−1) + 3(n−1)·M(n−2))/(n+2)" },
  "seq-h13": { p: "combinatorial",       t: "Integer partitions",              f: "p(n) = number of partitions of n" },
  "seq-h14": { p: "number-theoretic",    t: "Sum of divisors σ(n)",            f: "σ(n) = sum of all divisors of n" },
  "seq-h15": { p: "number-theoretic",    t: "Euler's totient φ(n)",            f: "φ(n) = count of k ≤ n with gcd(k,n)=1" },
  "seq-h16": { p: "prime-selection",     t: "Squares of consecutive primes",   f: "p(n)²: 2², 3², 5², 7², 11², 13², 17²" },
  "seq-h17": { p: "factorial",           t: "Factorial plus one",              f: "a(n) = n! + 1" },
  "seq-h18": { p: "compound",            t: "Fibonacci × position",            f: "a(n) = F(n) × n" },
  "seq-h19": { p: "compound",            t: "n-th prime + n",                  f: "a(n) = p(n) + n" },
  "seq-h20": { p: "digit-pattern",       t: "Add number to its reverse",       f: "a(n) = a(n−1) + reverse(a(n−1))" },
  "seq-h21": { p: "recursive-product",   t: "Sum + product of previous two",   f: "a(n) = a(n−1) + a(n−2) + a(n−1)·a(n−2) = (a+1)(b+1)−1" },
  "seq-h22": { p: "digit-pattern",       t: "Digit product + digit sum",       f: "a(n) = digit_prod(a(n−1)) + digit_sum(a(n−1))" },
  "seq-h23": { p: "famous-diff",         t: "2nd differences are primes",      f: "Δ² = 2, 3, 5, 7, 11, 13 (primes)" },
  "seq-h24": { p: "arithmetic-2nd-diff", t: "n² + n + 1",                     f: "Δ = 4, 6, 8, 10, 12, 14 (+2)" },
  "seq-h25": { p: "compound",            t: "2ⁿ + n²",                        f: "Sum of exponential and polynomial" },
  "seq-h26": { p: "power-pattern",       t: "3ⁿ − 2ⁿ",                       f: "Difference of two exponentials" },
  "seq-h27": { p: "prime-selection",     t: "Primorial (product of primes)",   f: "p₁·p₂·…·pₙ" },
  "seq-h28": { p: "interleaved",         t: "Fibonacci / Tribonacci",          f: "Odd: Fibonacci. Even: Tribonacci" },
  "seq-h29": { p: "progressive-ops",     t: "Ops use successive primes",       f: "×2, +3, ×5, +7, ×11, +13" },
  "seq-h30": { p: "cyclic-ops",          t: "5-cycle: +2, ×2, −3, ×3, −5",   f: "Operations repeat every 5 terms" },
  "seq-h31": { p: "cyclic-ops",          t: "4-cycle: ×2, +1, ×3, −4",        f: "Operations repeat every 4 terms" },
  "seq-h32": { p: "progressive-ops",     t: "Growing 3-cycle blocks",          f: "Block k: ×k, +k, −k. Ops escalate." },
  "seq-h33": { p: "progressive-ops",     t: "Multiplier changes every 3",      f: "×2 thrice, ×3 thrice, ×4 thrice…" },
  "seq-h34": { p: "progressive-ops",     t: "×1, +2, ×3, +4, ×5, +6",        f: "Odd ops multiply, even ops add" },
  "seq-h35": { p: "factorial",           t: "Signed factorials",               f: "(−1)^(n+1) × n!" },
  "seq-h36": { p: "famous-diff",         t: "2nd diffs are natural numbers",   f: "Δ² = 1, 2, 3, 4, 5, 6" },
  "seq-h37": { p: "famous-diff",         t: "Differences are oblong numbers",  f: "Δ = n(n+1): 2, 6, 12, 20, 30, 42" },
  "seq-h38": { p: "famous-diff",         t: "Differences are n² + 1",          f: "Δ = 2, 5, 10, 17, 26, 37" },
  "seq-h39": { p: "geometric-diff",      t: "Differences are Mersenne numbers",f: "Δ = 2ⁿ − 1: 1, 3, 7, 15, 31, 63" },
  "seq-h40": { p: "combinatorial",       t: "Partial sums of Catalan",         f: "Σ C(k) for k = 0…n" },
  "seq-h41": { p: "power-pattern",       t: "Sum of first n cubes",            f: "(n(n+1)/2)²" },
  "seq-h42": { p: "linear-recurrence",   t: "Partial sums of Fibonacci",       f: "Σ F(k) for k = 1…n" },
  "seq-h43": { p: "combinatorial",       t: "Bell numbers",                    f: "Number of set partitions of {1…n}" },
  "seq-h44": { p: "digit-pattern",       t: "Add digit sum to self",           f: "a(n) = a(n−1) + digit_sum(a(n−1))" },
  "seq-h45": { p: "factorial",           t: "Factorial differences",           f: "a(n) = n! − (n−1)! = (n−1)·(n−1)!" },
  "seq-h46": { p: "famous-diff",         t: "Differences are pentagonal",      f: "Δ = 1, 5, 12, 22, 35, 51 (pentagonal)" },
  "seq-h47": { p: "progressive-ops",     t: "Add n! to running total",         f: "a(n) = a(n−1) + n!" },
  "seq-h48": { p: "recursive-product",   t: "Sylvester's sequence",            f: "a(n) = a(n−1)² − a(n−1) + 1" },
  "seq-h49": { p: "compound",            t: "Recamán's sequence",              f: "a(n) = a(n−1)−n if new & positive, else a(n−1)+n" },
  "seq-h50": { p: "digit-pattern",       t: "Binary popcount",                 f: "a(n) = number of 1-bits in binary(n)" }
};
